name: CI
on:
  push:
    tags:
      - v*

jobs:
  test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        go: ["1.15"]
    steps:
      - name: Set up ${{matrix.go}}
        uses: actions/setup-go@v2
        with:
          go-version: ${{matrix.go}}

      - name: Check out repotsitory
        uses: actions/checkout@v1

      - name: Install packages
        run: go mod download

      - name: Run test
        run: go test -v ./...

  docker-build:
    runs-on: ubuntu-18.04
    env:
      DOCKER_IMAGE_NAME: docker-app
    steps:
      - name: Build and push docker image
        run: |
          docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
          TAG=$(echo $GITHUB_REF | grep -o "[0-9][\.].*")
          DOCKER_IMAGE=${{ secrets.DOCKER_REGISTRY }}/${ DOCKER_IMAGE_NAME }:$TAG
          docker build -t $DOCKER_IMAGE .
          docker push $DOCKER_IMAGE
