name: CI
on:
  push:
    branches:
      - main

jobs:
  test:
    name: unit test
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        go: ["1.15", "1.14"]
    steps:
      - name: Set up Go ${{matrix.go}}
        uses: actions/setup-go@v2
        with:
          go-version: ${{matrix.go}}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: go mod download

      - name: Test code
        run: go test -v ./...
